---
version: 3
# Note the version here is the ansible builder template version
# and has nothing to do with your ee image version tag
images:
  base_image:
    name: quay.io/centos/centos:stream9
#
dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      # These are from awx.ee
      - name: amazon.aws
      - name: ansible.posix
      - name: ansible.windows
      - name: awx.awx
      - name: azure.azcollection
        version: "==2.7.0"
      - name: community.vmware
      - name: google.cloud
      - name: kubernetes.core
      - name: kubevirt.core
      - name: openstack.cloud
      - name: ovirt.ovirt
      - name: redhatinsights.insights
      - name: theforeman.foreman
      # These are what I added
      - name: ansible.netcommon
      - name: ansible.network
      - name: ansible.security
      - name: ansible.snmp
      - name: ansible.utils
      - name: ansible.yang
      - name: cloud.common
      - name: cloud.terraform
      - name: community.crypto
      - name: community.general
      - name: community.windows
      - name: containers.podman
  system: |
    # These are from awx-ee modified slightly for my use
    git-core [platform:rpm]
    python3.11-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    openssl-devel [platform:rpm compile]
    #   Build Tools - Changed to RPM only so we can dnf remove later
    cmake [platform:rpm]
    gcc [platform:rpm]
    gcc-c++ [platform:rpm]
    make [platform:rpm]
    # These are what I added
    libxml2-devel [platform:rpm]
  python: |
    # These are from awx-ee
    #   Changed ansible-sign from git compile to python install
    ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    receptorctl
    # These are what I added
    dnspython
    jsonpatch
    netaddr
    xmltodict
#
options:
  package_manager_path: /usr/bin/dnf
#
#additional_build_files:
#  - src: files/ansible.cfg
#    dest: configs
#
additional_build_steps:
#  prepend_base:
#  prepend_galaxy:
#  prepend_final:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    # The following are from ansible/awx-ee
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor && git lfs install --system
    # SymLink `python` -> `python3.11`
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.11 311 && alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 311
    # Remove build tools and clean
    - RUN dnf remove -y make cmake gcc gcc-c++ cpp && dnf clean all && rm -rf /tmp/*
