---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

#build_arg_defaults:
#  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      # These are in awx-ee
      - name: amazon.aws
        version: 6.3.0
      - name: ansible.posix
        version: 1.5.4
      - name: ansible.windows
        version: 2.1.0
      - name: awx.awx
        version: 23.0.0
      - name: azure.azcollection
        version: 1.17.0
      - name: community.vmware
        version: 3.9.0
      - name: google.cloud
        version: 1.2.0
      - name: kubernetes.core
        version: 2.4.0
      - name: openstack.cloud
        version: 2.1.0
      - name: ovirt.ovirt
        version: 3.1.3
      - name: redhatinsights.insights
        version: 1.0.8
      - name: theforeman.foreman
        version: 3.13.0
      # These are what I added
      - name: ansible.netcommon
        version: 5.1.2
      - name: ansible.utils
        version: 2.10.3
      - name: community.crypto
        version: 2.15.1
      - name: community.general
        version: 7.3.0
      - name: community.windows
        version: 2.0.0
      - name: containers.podman
        version: 1.10.3
  system: |
    # These are in awx-ee
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    python-unversioned-command [platform:rpm]
    unzip [platform:rpm]
    # These are what I added
  python: |
    # These are in awx-ee
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    # These are what I added
    # community.general.dig requires dnspython module but isnt installed by collecion
    dnspython

#options:
#  package_manager_path: /usr/bin/microdnf

#additional_build_files:
#  - src: files/ansible.cfg
#    dest: configs

additional_build_steps:
#  prepend_galaxy:
#    - ADD _build/configs/ansible.cfg ~/.ansible.cfg
#  prepend_final: |
#    RUN whoami
#    RUN cat /etc/os-release
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system

